version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./app.env
    networks:
      - backend_univ
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
    networks:
      - backend_univ
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
    networks:
      - backend_univ
  app:
    build: .
    container_name: golang_app
    ports:
      - '8000:8000'
    networks:
      - backend_univ
networks:
  backend_univ:
      driver: bridge
volumes:
  redisDB:
  progresDB:
