name: Deploy to Docker Hub and Railway

on:
  push:
    branches: [ tes ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file with secrets
        run: |
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{ vars.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ vars.PGADMIN_DEFAULT_PASSWORD }}" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "CLIENT_ORIGIN=${{ vars.CLIENT_ORIGIN }}" >> .env
          echo "REDIS_PASSWORD=${{ vars.REDIS_PASSWORD }}" >> .env
          echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> .env
          echo "JWT_PRIVATE_KEY=${{ vars.JWT_PRIVATE_KEY }}" >> .env
          echo "JWT_PUBLIC_KEY=${{ vars.JWT_PUBLIC_KEY }}" >> .env
          echo "ACCESS_TOKEN_EXPIRED_IN=15m" >> .env
          echo "ACCESS_TOKEN_MAXAGE=${{ vars.ACCESS_TOKEN_MAXAGE }}" >> .env
          echo "REFRESH_TOKEN_EXPIRED_IN=60m" >> .env
          echo "REFRESH_TOKEN_MAXAGE=${{ vars.REFRESH_TOKEN_MAXAGE }}" >> .env


      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}

      # - name: Install Railway
      #   run: npm i -g @railway/cli

      # - name: Deploy to Railway
      #   run: railway up
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
